"""add vacancy technologies

Revision ID: cdd19f1ce52e
Revises: f603995b3870
Create Date: 2026-08-07 12:08:45.965865
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cdd19f1ce52e'
down_revision: Union[str, None] = 'f603995b3870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет изменения к БД."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_id'), 'technologies', ['id'], unique=False)
    op.create_index(op.f('ix_technologies_name'), 'technologies', ['name'], unique=True)
    op.create_index(op.f('ix_technologies_slug'), 'technologies', ['slug'], unique=True)
    op.create_table('vacancy_technologies',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacancy_id', 'technology_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает изменения."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_technologies')
    op.drop_index(op.f('ix_technologies_slug'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_name'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_id'), table_name='technologies')
    op.drop_table('technologies')
    # ### end Alembic commands ###
