"""add notification sender

Revision ID: d9a0d0b595ec
Revises: b7e9fbb92c26
Create Date: 2026-08-17 13:33:25.055823
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd9a0d0b595ec'
down_revision: Union[str, None] = 'b7e9fbb92c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применяет изменения к БД."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатывает изменения."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_column('notifications', 'sender_name')
    op.drop_column('notifications', 'sender_id')
    # ### end Alembic commands ###
